### ISSUE TITLE
Rename to futures-openssl

### ISSUE THREAD

**Issue by cramertj** [tokio-rs/tokio-openssl#12]
This crate doesn't have any dependencies on the tokio runtime. @alexcrichton would you consider a rename for clarity? (it's tough to sort out at the moment which crates are usable on alternative executors and which are not, and keeping the naming straight would go a long way towards clearing this up)

**Comment by alexcrichton** [comment]
Certainly! I also don't mind transferring the repo to a new owner as I don't have time nowadays to maintain this. @cramertj I don't suppose you'd be interested would you?

(or maybe @sfackler you'd be ok moving into the `openssl` repo?)

**Comment by sfackler** [comment]
Yeah, I can move it into sfackler/rust-openssl.

**Comment by alexcrichton** [comment]
Ok thanks! I'm not personally too too interested in the history, so @sfackler want to import the crate and when that's done I'll archive this repository after updating docs to point to `futures-openssl`?

**Comment by cramertj** [comment]
\o/ Thanks to both of you! :)

**Comment by sfackler** [comment]
I think it might make the most sense to do this when futures 0.3 is released. Seem reasonable @cramertj?

**Comment by cramertj** [comment]
@sfackler I don't have a particular opinion about the release timeline-- seems fine to me either way!

**Comment by Darksonn** [comment]
This issue seems outdated. The crate does depend on Tokio.
