### ISSUE TITLE
Potentially move this into tokio org

### ISSUE THREAD

**Issue by LucioFranco** [tokio-rs/tokio-openssl#17]
Hey @alexcrichton, sorry for the ping! We have been slowly trying to take most of the main tls based tokio libs and move them into our main https://github.com/tokio-rs/tls repo so that we can have a single team maintain them and provide support for tls. Since, its a critical feature we'd like to ensure our users have a consistent experience and good support. I was curious if you would be open to this and us/@sfackler taking over ownership :)

**Comment by alexcrichton** [comment]
I would be ok doing this if @sfackler is ok with it as well.

**Comment by sfackler** [comment]
👍

**Comment by LucioFranco** [comment]
Great! Thanks, I will start this process this week and I'll coordinate with @sfackler on discord.

**Comment by benesch** [comment]
Is this still desirable? I'm happy to do the legwork if so.

**Comment by sfackler** [comment]
I'm still on board if the tokio folks are.

**Comment by LucioFranco** [comment]
Yeah, I'd love too, I don't currently have the time to move all the commits and give this repo the proper migration into the `tokio-rs/tls` lib, but if someone wants to take that on we can coordinate it.

**Comment by sfackler** [comment]
If you don't want to mess around with tree merges, just copy/pasting the source into the repo seems fine with me.

**Comment by benesch** [comment]
I’m happy to whip up a PR with the subtree stuff sorted out.

**Comment by LucioFranco** [comment]
@benesch I'd love that! Hit me up on discord to coordinate when you need it :) I can also give you collab access there too, if you're interested in helping maintain it.

@sfackler do you have a list of collaborators here that I should add to the tokio repo?

**Comment by sfackler** [comment]
I think it's basically just me.

**Comment by jacob-pro** [comment]
For consistency it might be good if this crate re-exports openssl, in the same way that the other tokio ssl crates re-export rustls/native-tls

**Comment by vahidmohsseni** [comment]
Are you still going to migrate this repo? 
I noticed that there is no update in a long time. Is this repo still valid and useable? 
@sfackler sorry to mention you here. But I think you are the maintainer of this repo. So, it is better to ask you first :)

**Comment by sfackler** [comment]
Moved!

**Comment by sfackler** [comment]
The repo is still valid and useable.
