### ISSUE TITLE
Clone SslStream

### ISSUE THREAD

**Issue by yovanoc** [tokio-rs/tokio-openssl#45]
Is there a way to clone an SslStream to put it in another tokio::spawn? or another way to have some heartbeat loop for exemple while continuing to read/send elsewhere ? thanks

**Comment by sfackler** [comment]
There is not.

**Comment by yovanoc** [comment]
Oh sad, it's a planned thing or not at all ?

**Comment by sfackler** [comment]
OpenSSL's stream type cannot be cloned.

You can potentially use something like https://docs.rs/tokio/latest/tokio/io/fn.split.html or write a task that handles all of the interaction with SslStream directly.

**Comment by yovanoc** [comment]
I've tried different things and don't manage to find a way.
The goal is to have an heartbeat every 10 secs on this ssl tcp connection, while we can still write and read elsewhere

```rust
    let (mut reader, mut writer) = split(stream);

    let mut app_auth = ProtoOaApplicationAuthReq::default();
    app_auth.client_id = client_id;
    app_auth.client_secret = client_secret;
    write_tcp(
        &mut writer,
        &app_auth,
        ProtoOaPayloadType::ProtoOaApplicationAuthReq as i32,
    )
    .await?;

    let handle_heartbeat = tokio::spawn(async move {
        // send heartbeat every 10 sec
        loop {
            sleep(Duration::from_secs(10)).await;
            let _heartbeat = ProtoHeartbeatEvent::default();
            // write_tcp(&mut writer, &heartbeat, ProtoPayloadType::HeartbeatEvent as i32).await.unwrap();
        }
    });
```

**Comment by sfackler** [comment]
Wrapping the writer in https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html is one option.

**Comment by yovanoc** [comment]
Your rock man, Arc + Mutex is perfect !
