### ISSUE TITLE
`SslStream::poll_read` creates a slice from potentially uninitialized data

### ISSUE THREAD

**Issue by jamesmunns** [tokio-rs/tokio-openssl#46]
Hi there, in the following code:

https://github.com/tokio-rs/tokio-openssl/blob/ebbd1280f75aa8031e71df2abb6e6253996a5978/src/lib.rs#L232-L237

`ReadBuf::unfilled_mut()` is called, which returns [potentially uninitialized data](https://docs.rs/tokio/latest/tokio/io/struct.ReadBuf.html#method.unfilled_mut). This is then used to create a `&mut [u8]`, which is used to call the [`Read::read`](https://doc.rust-lang.org/stable/std/io/trait.Read.html) method.

This seems to have been known to be unsound (or "improper") at the time based on the comment, but was done (temporarily?) for performance by @sfackler [in 2021](https://github.com/tokio-rs/tokio-openssl/commit/65e5c482bdb9cdca151430f7970f8c988ddf3982), who noted:

> This shouldn't be necessary, but it seems that tokio-codec doesn't
> properly track the initialization of its buffer and so the old logic
> resulted in a ton of overhead.

This seems to rely on the fact that openssl will not (should not?) ever read the data, however just creating the slice from uninit data is already unsound. Is this still necessary for performance, or have the other performance issues been addressed in the intervening years?

This snippet appears three times publicly, as far as I can tell from a quick search: https://grep.app/search?q=but%20rust-openssl

**Comment by sfackler** [comment]
I should probably just add a `fn read_uninit(&mut self, buf: &mut [MaybeUninit<u8>])` method to `openssl::ssl::SslStream` to avoid the sketchy buffer here.
